### ISSUE TITLE
Trademarks

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer.io#2]
@astanush A discussion with @toddross revealed the need for us to do two things within our logo files:
- Add the "™" symbol to "AQUIFER" in the logo. 
- Remove the "™" symbol and replace it with the "®" symbol after Drupal in the "Aquifer for Drupal" variant of the logo.

Would it be possible for you to do this and then re-export the two different logo types with these changes, and add them to this repo? I'm happy to re-create the GitHub README specific sizes with the new editions once the vector files are updated.

**Comment by astanush** [comment]
Logos updated in 850bfd9
- New EPS
- New SVGs (both versions)
- New 500px PNGs (renamed to omit "px" to match other names)
- New square logo SVG file

I didn't touch the 1456 or 2032 versions, but you should have everything you need to recreate them.

FYI, `aquifer-logo.eps` has two layers "lockup" and "for Drupal", so that you can have one artwork file to turn on/off the Drupal sub-branding layer, to export both versions.

**Comment by patrickocoffeyo** [comment]
@astanush excellent. Thank you so much!
