### ISSUE TITLE
Logo has misaligned planes. 

### ISSUE THREAD

**Issue by mattgrill** [aquifer/aquifer.io#3]
The top and front planes do not align correctly leaving a minor visual glitch. 

![aquifer _for_drupal](https://cloud.githubusercontent.com/assets/1090713/10974158/88fa3434-8395-11e5-9fd0-8e31ef4ab05f.png)

**Comment by astanush** [comment]
I think these were versions generated by @patrickocoffeyo? Not sure if he's using Inkscape or something, because when I export a 1456px version from Illustrator it doesn't have this issue.

In any case, I'm also updating the logo to have the "L" in Drupal right aligned with the "R" in Aquifer — so I'll include new versions for all the sizes.
